gpu_mode=True
visualize=False
save_every_iters=0
display_every_iters=3
work_dir='./outputs' #directory for saving results
data_dir='./data' #directory for downloading datasets
save_on_epochs=[]
show_data_mean=False
num_workers=4